/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DataMonetizerBase__factory } from "./DataMonetizerBase__factory";
export { IERC20__factory } from "./IERC20__factory";
