/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export type AssetSubscribeDetailStruct = {
  currency: string;
  amount: BigNumberish;
};

export type AssetSubscribeDetailStructOutput = [string, BigNumber] & {
  currency: string;
  amount: BigNumber;
};

export interface MonthlySubscribeModuleInterface extends utils.Interface {
  functions: {
    "SUBSCRIBE_ACTION()": FunctionFragment;
    "getAssetSubscribeDetail(bytes32)": FunctionFragment;
    "initializeSubscribeModule(bytes32,bytes)": FunctionFragment;
    "processSubscribe(bytes32,address,bytes)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "SUBSCRIBE_ACTION"
      | "getAssetSubscribeDetail"
      | "initializeSubscribeModule"
      | "processSubscribe"
      | "supportsInterface"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "SUBSCRIBE_ACTION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAssetSubscribeDetail",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeSubscribeModule",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "processSubscribe",
    values: [BytesLike, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "SUBSCRIBE_ACTION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAssetSubscribeDetail",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeSubscribeModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processSubscribe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;

  events: {};
}

export interface MonthlySubscribeModule extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MonthlySubscribeModuleInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    SUBSCRIBE_ACTION(overrides?: CallOverrides): Promise<[string]>;

    getAssetSubscribeDetail(
      assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[AssetSubscribeDetailStructOutput]>;

    initializeSubscribeModule(
      assetId: BytesLike,
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    processSubscribe(
      assetId: BytesLike,
      subscriber: string,
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  SUBSCRIBE_ACTION(overrides?: CallOverrides): Promise<string>;

  getAssetSubscribeDetail(
    assetId: BytesLike,
    overrides?: CallOverrides
  ): Promise<AssetSubscribeDetailStructOutput>;

  initializeSubscribeModule(
    assetId: BytesLike,
    data: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  processSubscribe(
    assetId: BytesLike,
    subscriber: string,
    data: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    SUBSCRIBE_ACTION(overrides?: CallOverrides): Promise<string>;

    getAssetSubscribeDetail(
      assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<AssetSubscribeDetailStructOutput>;

    initializeSubscribeModule(
      assetId: BytesLike,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    processSubscribe(
      assetId: BytesLike,
      subscriber: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    SUBSCRIBE_ACTION(overrides?: CallOverrides): Promise<BigNumber>;

    getAssetSubscribeDetail(
      assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initializeSubscribeModule(
      assetId: BytesLike,
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    processSubscribe(
      assetId: BytesLike,
      subscriber: string,
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    SUBSCRIBE_ACTION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAssetSubscribeDetail(
      assetId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initializeSubscribeModule(
      assetId: BytesLike,
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    processSubscribe(
      assetId: BytesLike,
      subscriber: string,
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
