/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IDataTokenFactory,
  IDataTokenFactoryInterface,
} from "../IDataTokenFactory";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "originalContract",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "dataToken",
        type: "address",
      },
    ],
    name: "DataTokenCreated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "initVars",
        type: "bytes",
      },
    ],
    name: "createDataToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IDataTokenFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IDataTokenFactoryInterface {
    return new utils.Interface(_abi) as IDataTokenFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDataTokenFactory {
    return new Contract(address, _abi, signerOrProvider) as IDataTokenFactory;
  }
}
